let animalsdata =[
    {id: "animalslion", 
    name:"lion", 
    price: 6000, 
    img: "pics/lillion.png",
    alternate:"a quick doodle of a lion",
    description: "show that your the king with this powerfull beast! keep in mind the upkeep and possibly a great life insurance policy."},

    {id: "animalsflamingo",
    name:"flamingo", 
    price: 3000, 
    img: "pics/lilflamingo.png",
    alternate:"a quick flamingo drawing",
    description: "elegant bird is the perfect addition for a backyard pond"},

    {id: "animalssnake",
    name: "snake",
    price: 100,
    img: "pics/snake.jpg",
    alternate: "an AI python snake.",
    description: "for the reptile lovers, our snakes are docile and have vivid colors. can be fed live or frozen food."},

    {id: "animalsbunny",
    name: "bunny",
    price: 25,
    img: "pics/bunny.jpg",
    alternate:"picture of a black bunny",
    description:"adorable, easy, and kids love it"},
   
    {id:"animalscheetah",
    name: "cheetah",
    price: 50000,
    img:"pics/cheetah.jpg",
    alternate:"headshot of a georgous cheetah",
    description:"beautiful, great for racing, cubs can even be kind of tamed."},
    
    {id:"animalsseahorse",
    name:"seahorse",
    price: 1000,
    img:"pics/seahorse.jpg",
    alternate:"picture of a pink seahorse against purple corals",
    description: "price includes the tank and basic equipment."},

    {id:"animalshorse",
    name:"horse",
    price: 7000,
    img:"pics/horses.jpg",
    alternate:"picture of a red, a black, and a white horse in a field",
    description: "beautiful horses. many breeds and colors.  great quality and temperment, raised to be family pets. many are broke to ride, though for fulls or yearlings you're on your own."}
]