let animalsdata =[
    {id: "animalslion", 
    name:"lion", 
    price: 6000, 
    img: "pics/ailion.jpg",
    alternate:"image of an AI lion",
    description: "show that your the king with this powerfull beast! keep in mind the upkeep and possibly a great life insurance policy."},

    {id: "animalssnake",
    name: "snake",
    price: 100,
    img: "pics/snake.jpg",
    alternate: "an AI python snake.",
    description: "for the reptile lovers, our snakes are docile and have vivid colors. can be fed live or frozen food."},

    {id: "animalsbunny",
    name: "bunny",
    price: 25,
    img: "pics/bunny.jpg",
    alternate:"picture of a black bunny",
    description:"adorable, easy, and kids love it"},
   
    {id:"animalscheetah",
    name: "cheetah",
    price: 50000,
    img:"pics/cheetah.jpg",
    alternate:"headshot of a georgous cheetah",
    description:"beautiful, great for racing, cubs can even be kind of tamed."},
    
    {id:"animalsseahorse",
    name:"seahorse",
    price: 1000,
    img:"pics/aiseahorse.jpg",
    alternate:"picture of a pink seahorse against purple corals",
    description: "price includes the tank and basic equipment."},

    {id:"animalshorse",
    name:"horse",
    price: 7000,
    img:"pics/horses.jpg",
    alternate:"picture of a red, a black, and a white horse in a field",
    description: "beautiful horses. many breeds and colors.  great quality and temperment, raised to be family pets. many are broke to ride, though for fulls or yearlings you're on your own."},

    {id:"animalsbuffalo",
    name:"buffalo",
    price: 4000,
    img:"pics/buffalo.jpg",
    alternate:"picture of a buffalo",
    description: "pwerfull all american bison, heard animal will want two or more. have a live piece of american history on your land."},

    {id:"animalsemu",
    name:"emu",
    price: 200,
    img:"pics/emew.jpg",
    alternate:"picture of an emu",
    description: "large and entertaining bird. It's a great deal, and easier to keep than other exotics i'm assuming."},

    {id:"animalskoi",
    name:"koi fish",
    price: 1990,
    img:"pics/koifish.jpg",
    alternate:"picture of multiple koi fish",
    description: "generously cheap price for great quality fish. many colors and patterns all for the same low price."},

    {id: "animalsflamingo",
    name:"flamingo", 
    price: 3000, 
    img: "pics/aiflamingo.jpg",
    alternate:"image of an AI flamingo",
    description: "elegant bird is the perfect addition for a backyard pond. we totally have real birds. dont look at the picture too close. just take our word for it."},

    {id:"animalscat",
    name:"house cat",
    price: 0,
    img:"pics/cat.jpg",
    alternate:"picture of orange cat",
    description: "mostly tamed house cats. wide range of personalities. we have too many, please just take them. they're free. take a couple."},

    {id:"animalsmacaw",
    name:"macaw",
    price: 10000,
    img:"pics/macaw.jpg",
    alternate:"picture of a blue macaw",
    description: "beautiful inteligent bird can learn to speak and learn many tricks can be a lifelong close companion. why bother with dogs, your rich now."},
]

let housesdata = [

  {id:"homeidaho",
    name:"home",
    price: 495000,
    img:"pics/495,000.webp",
    alternate:"house with snow in front",
    description: "4 bed 3 bath semi fenced spacous yard. 1 car garadge."},

    {id:"lilred",
    name:"cute lil red",
    price: 290000,
    img:"pics/cutelilredhouse.webp",
    alternate:"red house",
    description: "3 bed 3 bath. 1 acre lot. seperate 2 car gradge. built in the 20s.. as in a hundred years ago."},

    {id:"bluehouse",
    name:"blue house",
    price: 475000,
    img:"pics/bluehouse.webp",
    alternate:"blue house",
    description: "beaautiful 3 bed 3 bath. 2 car garadge. 2 story plus basement."},

    {id:"cabin",
    name:"cabin",
    price: 285000,
    img:"pics/cabin.webp",
    alternate:"aincent cabin in a birch forest",
    description: "2 bed 2 bath. 40 acre lot. aincent. plenty of space for allll of the animals. could get away with growing weed or murder out here."},

    {id:"obsurd",
    name:"house",
    price: 578800,
    img:"pics/obsurd.webp",
    alternate:"plain house",
    description: "2 bed 1 bath. fenced in back yard. fine. price is a bit obsurd if you ask me."},

    {id:"style",
    name:"modern style",
    price: 975000,
    img:"pics/style.webp",
    alternate:"modern looking house",
    description: "if you want the most stylish home and not a damn thing else, this is the one for you! 4 bed 4 bath island with a sink, masive back patio, spiral staircase and all."},
]
  /*  {id:"",
    name:"",
    price: 0,
    img:"",
    alternate:"",
    description: ""},   */
